version: "3"
services:
        sopoware-panoptes:
                # I really don't wanted to, but for the bluetooth...
                privileged: true
                ports:
                        - "80:80"
                container_name: sopoware-panoptes
                volumes: 
                        - /tmp/argus_socket:/tmp/argus_socket
                        - /sys:/sys
                        - /dev/bus/usb:/dev/bus/usb
                        - /var/run/dbus:/var/run/dbus
                        - /sys/class/bluetooth:/sys/class/bluetooth
                        - /var/lib/bluetooth:/var/lib/bluetooth
                devices:
                        - /dev/gpiochip0:/dev/gpiochip0
                        - /dev/gpiochip1:/dev/gpiochip1
                build: 
                        context: .
                        dockerfile: ./Dockerfile
                        args:
                                MODE: 1
                                COLOR_SHIFT: 0
                                GPIO_PIN: 31
                                SIDEWALK_CLASS: 36
                        
                        # Mode
                        #   0 - No printing, only prediction + determine loop 
                        #   1 - prediction + determine loop + Debugging results printed + prediction results on port 80
                        #   2 - Recording mode
                        #   3 - Same as Mode 1, but every camera frames and predictions are saved in ./trt/save/

                image: sopoware-panoptes:latest

                # TODO : Is there a way to set the --group-add when the
                #        image is starting with 'docker-compose run'?

                # R32 (release), REVISION: 5.1, GCID: 27362550, BOARD: t210ref, EABI: aarch64, DATE: Wed May 19 18:07:59 UTC 2021
                #       docker-compose version is 1.17, If it is installed from apt-get.
                #       1.17 does not support to set runtime in docker-compose,
                #       You have to manually set 'runtime' when the image is starting.
                #       or, You could just build and install recent version of docker-compose

                # Because of this, you cannot just use 'docker-compose up'.
                
                #runtime: nvidia works on 1.27.0+
                #deploy... works on 1.28.0+

                #runtime: nvidia
                #deploy:
                #        resources:
                #                reservations:
                #                        devices:
                #                                - driver: nvidia
                #                                  count: 1
                #                                  capabilities: [gpu]
